FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_USER_API_URL=/user-api
ARG VITE_EVENT_API_URL=/event-api/api/v1
ARG VITE_GOOGLE_CLIENT_ID=
ARG VITE_FACEBOOK_APP_ID=
ARG VITE_OAUTH_REDIRECT_BASE_URL=

ENV VITE_USER_API_URL=$VITE_USER_API_URL
ENV VITE_EVENT_API_URL=$VITE_EVENT_API_URL
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_FACEBOOK_APP_ID=$VITE_FACEBOOK_APP_ID
ENV VITE_OAUTH_REDIRECT_BASE_URL=$VITE_OAUTH_REDIRECT_BASE_URL

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]